waypoints:
    - position:
        position_x: -2.00008
        position_y: -0.499657
        position_z: -0.00100139
        orientation_x: -1.74562e-05
        orientation_y: 0.00385307
        orientation_z: 0.00269821
        orientation_w: 0.999989
    - position:
        position_x: -1.25613
        position_y: -0.485961
        position_z: -0.00100192
        orientation_x: -5.83318e-05
        orientation_y: 0.00385687
        orientation_z: 0.0134215
        orientation_w: 0.999902
    - position:
        position_x: -0.51919
        position_y: -0.443441
        position_z: -0.00100176
        orientation_x: 0.000266068
        orientation_y: 0.00384672
        orientation_z: -0.0708186
        orientation_w: 0.997482
    - position:
        position_x: 0.0324291
        position_y: -0.517345
        position_z: -0.00100198
        orientation_x: 0.000225441
        orientation_y: 0.00385095
        orientation_z: -0.0605042
        orientation_w: 0.99816
