waypoints:
    - position:
        position_x: -2.00003
        position_y: -0.499919
        position_z: -0.00100139
        orientation_x: -9.51599e-06
        orientation_y: 0.0038531
        orientation_z: 0.000637074
        orientation_w: 0.999992
    - position:
        position_x: -1.53808
        position_y: -0.480609
        position_z: -0.00100153
        orientation_x: 0.000135853
        orientation_y: 0.00385138
        orientation_z: -0.0373503
        orientation_w: 0.999295
    - position:
        position_x: -1.08371
        position_y: -0.50358
        position_z: -0.00100141
        orientation_x: -3.26861e-05
        orientation_y: 0.00385322
        orientation_z: 0.00663613
        orientation_w: 0.999971
    - position:
        position_x: -0.634671
        position_y: -0.478268
        position_z: -0.00100197
        orientation_x: 0.000170833
        orientation_y: 0.00385377
        orientation_z: -0.0461538
        orientation_w: 0.998927
    - position:
        position_x: -0.190017
        position_y: -0.529788
        position_z: -0.00100118
        orientation_x: 0.000188041
        orientation_y: 0.00384582
        orientation_z: -0.0515477
        orientation_w: 0.998663
    - position:
        position_x: 0.26676
        position_y: -0.552489
        position_z: -0.00100094
        orientation_x: -0.000446063
        orientation_y: 0.00382237
        orientation_z: 0.113494
        orientation_w: 0.993531
    - position:
        position_x: 0.542974
        position_y: -0.191465
        position_z: -0.00100153
        orientation_x: -0.00246535
        orientation_y: 0.00296219
        orientation_z: 0.638209
        orientation_w: 0.769854
    - position:
        position_x: 0.570116
        position_y: 0.255862
        position_z: -0.00100109
        orientation_x: -0.0027425
        orientation_y: 0.00270267
        orientation_z: 0.710452
        orientation_w: 0.703735
    - position:
        position_x: 0.577973
        position_y: 0.705514
        position_z: -0.00100151
        orientation_x: -0.0026904
        orientation_y: 0.00275939
        orientation_z: 0.696607
        orientation_w: 0.717442
    - position:
        position_x: 0.531151
        position_y: 1.15045
        position_z: -0.00100112
        orientation_x: -0.00303517
        orientation_y: 0.00236989
        orientation_z: 0.787371
        orientation_w: 0.616467
    - position:
        position_x: 0.312019
        position_y: 1.54809
        position_z: -0.00100137
        orientation_x: -0.00358196
        orientation_y: 0.00141821
        orientation_z: 0.928938
        orientation_w: 0.370215
    - position:
        position_x: -0.102952
        position_y: 1.75759
        position_z: -0.00100113
        orientation_x: -0.00382957
        orientation_y: 0.00040323
        orientation_z: 0.994233
        orientation_w: 0.107174
    - position:
        position_x: -0.549398
        position_y: 1.81212
        position_z: -0.00100146
        orientation_x: -0.00385002
        orientation_y: 0.000161244
        orientation_z: 0.999031
        orientation_w: 0.0438335
    - position:
        position_x: -1.00823
        position_y: 1.76015
        position_z: -0.00100162
        orientation_x: -0.00377887
        orientation_y: -0.000760633
        orientation_z: 0.980758
        orientation_w: -0.195192
    - position:
        position_x: -1.38385
        position_y: 1.51489
        position_z: -0.0010018
        orientation_x: -0.00357319
        orientation_y: -0.00144961
        orientation_z: 0.927473
        orientation_w: -0.373869
    - position:
        position_x: -1.64888
        position_y: 1.12979
        position_z: -0.00100122
        orientation_x: -0.00321664
        orientation_y: -0.00211766
        orientation_z: 0.836736
        orientation_w: -0.547592
    - position:
        position_x: -1.76637
        position_y: 0.691866
        position_z: -0.00100146
        orientation_x: -0.0029002
        orientation_y: -0.00253784
        orientation_z: 0.753631
        orientation_w: -0.657287
    - position:
        position_x: -1.77048
        position_y: 0.230857
        position_z: -0.00100168
        orientation_x: -0.00262702
        orientation_y: -0.00282649
        orientation_z: 0.681478
        orientation_w: -0.731829
    - position:
        position_x: -1.77001
        position_y: 0.224299
        position_z: -0.00100154
        orientation_x: -0.00262817
        orientation_y: -0.00281905
        orientation_z: 0.683373
        orientation_w: -0.730059
